# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_description', models.CharField(max_length=500)),
                ('creator_name', models.CharField(max_length=50)),
                ('creator_username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='group_user_pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gup_group_name', models.CharField(max_length=50)),
                ('gup_username', models.IntegerField()),
            ],
        ),
    ]
