# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creategroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempModel_name', models.CharField(max_length=50)),
            ],
        ),
    ]
