# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creategroup', '0002_tempmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_user_pair',
            name='gup_username',
            field=models.CharField(max_length=50),
        ),
    ]
