# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='delete_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.CharField(default='DEFAULT USERNAME', max_length=150),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_name',
            field=models.CharField(default='DEFAULT COMPANY', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('INV_USR', 'Investor'), ('CMP_USR', 'Company')], default='INV_USR', max_length=7),
        ),
    ]
