# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170329_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ceo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='company_country',
        ),
        migrations.RemoveField(
            model_name='report',
            name='company_ctp',
        ),
        migrations.RemoveField(
            model_name='report',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='company_industry',
        ),
        migrations.RemoveField(
            model_name='report',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='company_projects',
        ),
        migrations.RemoveField(
            model_name='report',
            name='company_sector',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('INV_USR', 'Investor'), ('CMP_USR', 'Company')], default='INV_USR', max_length=7),
        ),
    ]
