# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170330_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('CMP_USR', 'Company'), ('INV_USR', 'Investor')], default='INV_USR', max_length=7),
        ),
    ]
