# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170424_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company_phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='report',
            name='private',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Yes', max_length=1),
        ),
    ]
