# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170424_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company_country',
            field=models.CharField(default='DEFAULT COUNTRY', max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='report',
            name='private',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Yes', max_length=1),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('INV_USR', 'Investor'), ('CMP_USR', 'Company')], default='INV_USR', max_length=7),
        ),
    ]
