# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20170501_1726'),
        ('registration', '0007_auto_20170501_1624'),
    ]

    operations = [
    ]
